version: "3.8"
services:
  app:
    build: .
    container_name: note-api
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/note-api
    command: air main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
